
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meu primeiro site</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: rgb(251, 248, 255);
        }

        header {
            background-color: rgb(232, 17, 132);
            color: white;
            margin: 0;
            padding: 20px;
            text-align: center;
            font-size: 24px;
        }

        nav {
            background-color: blueviolet;
            padding: 10px;
            text-align: center;
        }

        nav a {
            background-color: aliceblue;
            text-decoration: none;
            color: black;
            margin: 0 15px;
            font-size: 18px;
            padding: 5px 10px;
            border-radius: 5px;
        }

        .container {
            padding: 20px;
            text-align: center;
        }

        .produto {
            display: inline-block;
            margin: 15px;
            padding: 10px;
            border: 1px solid #ccc;
            background-color: white;
            border-radius: 8px;
        }

        .produto img {
            width: 150px;
            height: 150px;
        }

        .btn {
            background-color: #ff69b4;
            color: white;
            border: none;
            padding: 10px;
            cursor: pointer;
            margin-top: 10px;
            border-radius: 5px;
        }

        .btn:hover {
            background-color: #ff1493;
        }

        .carrinho {
            margin-top: 20px;
            padding: 10px;
            background-color: white;
            border-radius: 8px;
            text-align: center;
            border: 1px solid #ccc;
        }

        footer {
            background-color: #ff1493;
            color: white;
            text-align: center;
            padding: 20px;
        }
    </style>
</head>
<body>
    <header>Loja de Maquiagem</header>
    
    <nav>
        <a href="#home">Home</a>
        <a href="#produtos">Produtos</a>
        <a href="#carrinho">Carrinho</a>
        <a href="#contato">Contato</a>
    </nav>

    <section id="home" class="container">
        <h1>Bem-vindo à nossa loja de maquiagem!</h1>
        <p>Encontre os melhores produtos para realçar sua beleza.</p>
    </section>

    <section id="produtos" class="container">
        <h2>Nossos Produtos</h2>
        <div class="produto">
            <img src="https://via.placeholder.com/150" alt="Batom">
            <h3>Batom Matte</h3>
            <p>R$ 29,90</p>
            <button class="btn" onclick="adicionarAoCarrinho('Batom Matte', 29.90)">Adicionar ao Carrinho</button>
        </div>
        <div class="produto">
            <img src="https://via.placeholder.com/150" alt="Base">
            <h3>Base Líquida</h3>
            <p>R$ 49,90</p>
            <button class="btn" onclick="adicionarAoCarrinho('Base Líquida', 49.90)">Adicionar ao Carrinho</button>
        </div>
    </section>

    <section id="carrinho" class="carrinho">
        <h2>Carrinho de Compras</h2>
        <ul id="itens-carrinho"></ul>
        <p><strong>Total:</strong> R$ <span id="total">0.00</span></p>
    </section>

    <section id="contato" class="container">
        <h2>Contato</h2>
        <p>Email: contato@lojamaquiagem.com</p>
        <p>Telefone: (11) 99999-9999</p>
    </section>

    <footer>
        <p>&copy; 2025 Loja de Maquiagem. Todos os direitos reservados.</p>
    </footer>

    <script>
        let total = 0;
        function adicionarAoCarrinho(nome, preco) {
            const lista = document.getElementById("itens-carrinho");
            const item = document.createElement("li");
            item.textContent = `${nome} - R$ ${preco.toFixed(2)}`;
            lista.appendChild(item);
            total += preco;
            document.getElementById("total").textContent = total.toFixed(2);
        }
    </script>
</body>
</html>
